pusherchat/urls.py
from django.conf.urls import patterns, include, url

from chat.views import MessageCreateView
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', MessageCreateView.as_view(template_name='index.html'), name='home'),
    # url(r'^pusherchat/', include('pusherchat.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

chat/models.py
from django.db import models

# Create your models here.

chat/views.py
# Create your views here.
from django.views.generic import FormView
from django import forms, http

import pusher


class MessageForm(forms.Form):
    RED, BLUE, YELLOW = map(str, range(3))
    CHATROOMS = (
        (RED, 'Red'),
        (BLUE, 'Blue'),
        (YELLOW, 'Yellow')
    )
    name = forms.CharField(widget=forms.HiddenInput)
    message = forms.CharField()
    chatroom = forms.ChoiceField(choices=CHATROOMS)


class MessageCreateView(FormView):
    form_class = MessageForm

    template_name = 'index.html'

    def form_valid(self, form):
        message = form.cleaned_data.get('message')
        chatroom = form.cleaned_data.get('chatroom')
        name = form.cleaned_data.get('name')
        p = pusher.pusher_from_url()
        if p[chatroom].trigger('new-message', {'id': '1', 'name': name, 'message': message}):
            return http.HttpResponse('Ok')
        return self.form_invalid(form=form)

    def form_invalid(self, form):
        return http.HttpResponse('Error')

    def get_initial(self):
        return {
            'name': 'Anonym'
        }

chat/templates/index.html
<!DOCTYPE html>
<html>
  <head>
    <title>Pusher Django</title>
  </head>
  <body>
    <a href="https://github.com/pedroburon/pusherdjangochat"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_orange_ff7600.png" alt="Fork me on GitHub"></a>

    <h1>Pusher Django</h1>
    <p>Django chat using pusher, open another tab (or window) and chat with yourself.</p>
    <form method="post" id="chat-form">{% csrf_token %}
      {{ form.as_p }}
      <input type="submit" />
    </form>

    <dl id="messages">
    </dl>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" type="text/javascript"></script>
    <script src="http://js.pusher.com/1.12/pusher.min.js" type="text/javascript"></script>
    <script type="text/javascript">
      // Enable pusher logging - don't include this in production
      Pusher.log = function(message) {
        if (window.console && window.console.log) window.console.log(message);
      };

      // Flash fallback logging - don't include this in production
      WEB_SOCKET_DEBUG = true;

      var pusher = new Pusher('8ad6890ac7bbe9087a0a');
      var channel = null;
    </script>
    <script type="text/javascript">
      var append_message = function(data) {
        $('#messages').append('<dt id="message-dt-"' + data['id'] + '>' + data['name'] + ':</dt>')
                      .append('<dd id="message-dd-"' + data['id'] + '>' + data['message'] + '</dt>')
      }
      function subscribe_to_chatroom(name) {
        if (channel != null)
          pusher.unsubscribe(channel.name)
        channel = pusher.subscribe($('#id_chatroom').val())
        channel.bind('new-message', append_message)
      }
      jQuery(function($) {
        var name = '';
        while (name == '' || name == null) {
          name = window.prompt("Your name", null);
          if (name != null)
             name = name.trim()
        }
        $('#id_name').val(name)
        subscribe_to_chatroom()
        $('#id_chatroom').change(function(e) {
          subscribe_to_chatroom($(this).val())
          $('#messages').html('')
        })
        $('#chat-form').submit(function(e) {
          e.preventDefault();
          var $this = $(this)
            , action = $this.attr('action')
            , data = $this.serialize();
    
          $.post(action, data, function(response) {
            if (response == 'Ok') {
              $('#id_message').val('')
            }
          })
        })
      })
    </script>
  </body>
</html>